from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='admin_dashboard'),
    path('login/', views.login_view, name='login'),
    path('demo_login/', views.demo_login, name='demo_login'),
    path('logout/', views.logout_view, name='logout'),
    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.create_user, name='create_user'),
    path('users/edit/<int:user_id>/', views.edit_user, name='edit_user'),
    path('categories/', views.categories_list, name='categories_list'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('categories/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('brands/', views.brands_list, name='brands_list'),
    path('brands/add/', views.add_brand, name='add_brand'),
    path('brands/edit/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('brands/delete/<int:brand_id>/', views.delete_brand, name='delete_brand'),
    path('products/', views.products_list, name='products_list'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('products/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('view_deleted_products/', views.view_deleted_products, name='view_deleted_products'),
    path('restore_product/<int:product_id>/', views.restore_product, name='restore_product'),
    path('view_deleted_categories/', views.view_deleted_categories, name='view_deleted_categories'),
    path('view_deleted_brands/', views.view_deleted_brands, name='view_deleted_brands'),
    path('restore_category/<int:category_id>/', views.restore_category, name='restore_category'),
    path('add_product_variant/<int:product_id>/', views.add_product_variant, name='add_product_variant'),
    # path('edit_product_variant/<int:product_id>/<int:variant_id>/', views.edit_product_variant, name='edit_product_variant'),
    # path('delete_product_variant/<int:product_id>/<int:variant_id>/', views.delete_product_variant, name='delete_product_variant'),
    # path('view_product_variants/<int:product_id>/', views.view_product_variants, name='view_product_variants'),
]
