# Generated by Django 5.1 on 2024-10-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0009_coupon_product_coupons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="star_date",
            new_name="start_date",
        ),
    ]
