# Generated by Django 5.1 on 2024-10-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0023_tag_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="ecommerce_app.category",
            ),
        ),
    ]
