# Generated by Django 5.1 on 2024-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0027_order_applied_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
