# Generated by Django 5.1 on 2024-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0035_productreturnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturnrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
